micronaut:
  router:
    static-resources:
      images:
        paths:
          - "classpath:views"

  application:
    name: quotes-frontend

  views:
    thymeleaf:
      suffix: ".html"
      enabled: true
      cacheable: false