micronaut:
  router:
    static-resources:
      images:
        paths:
          - "classpath:views"

  application:
    name: quotes-frontend

  views:
    thymeleaf:
      suffix: ".html"
      enabled: true

  http:
    services:
      characters:
        urls:
          - http://backend/characters
      quotes:
        urls:
          - http://backend/quotes
