micronaut:
  router:
    static-resources:
      images:
        paths:
          - "classpath:views"

  application:
    name: quotes-frontend

  views:
    thymeleaf:
      suffix: ".html"
      enabled: true

  http:
    services:
      backendcharacters:
        urls:
          - http://backend/characters
      backendquotes:
        urls:
          - http://backend/quotes
