FROM maven:3.5-jdk-8 as maven
COPY ./pom.xml ./pom.xml
RUN mvn dependency:go-offline --batch-mode

COPY ./src ./src
RUN mvn clean package --batch-mode

FROM openjdk:8-jre-alpine
COPY --from=maven target/quotes-backend-0.0.1.jar /myapp.jar
EXPOSE 8080
ENTRYPOINT java ${JAVA_OPTS} -jar /myapp.jar
