package com.example.quotesbackend;

import com.example.quotesbackend.model.Quote;
import com.example.quotesbackend.repository.QuoteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import javax.annotation.PostConstruct;
import java.util.Arrays;
import java.util.List;

@SpringBootApplication
public class QuotesBackendApplication {

    public static void main(String[] args) {
        SpringApplication.run(QuotesBackendApplication.class, args);
    }

    @Autowired
    private QuoteRepository quoteRepository;

    @PostConstruct
    public void init() {
        List<Quote> FRASES_SIMPSONS = Arrays.asList(
                new Quote("Homer Simpson", "¡Bart, con 10.000$ seremos millonarios! Podremos comprar todo tipo de cosas útiles, como… ¡Amor!"),
                new Quote("Homer Simpson", "¡Estúpido Flanders y su erotismo!"),
                new Quote("Homer Simpson", "¡No soy un mal tipo! Trabajo duro y quiero a mis hijos. Entonces, ¿Por qué tengo que pasarme medio domingo escuchando cómo voy a ir al infierno?"),
                new Quote("Homer Simpson", "¡Oh, mírame, Marge!!! Estoy haciendo feliz a mucha gente, soy el hombre mágico del país feliz de la casa de la gominola en la calle de la piruleta."),
                new Quote("Homer Simpson", "¡Parad! Sé lo que hay que hacer en estos casos… ¡Jumanji! ¡D’oh! ¿Por qué las cosas de las películas nunca funcionan?"),
                new Quote("Homer Simpson", "¡Por favor, no me comáis! Tengo mujer e hijos ¡Comeros a ellos!"),
                new Quote("Homer Simpson", "¡Qué suerte Marge!, nuestros hijos son cada vez más inteligentes, si tenemos otro podría construir una máquina del tiempo para viajar al pasado y no tener hijos."),
                new Quote("Homer Simpson", "¡Quiero mi bocadillo! ¡Quiero mi bocadillo!"),
                new Quote("Homer Simpson", "¡Yuhuuu! ¡Soy universitario! Ya no necesito el diploma del insti, que listo soy yo, que listo soy yo, que listo soy yo, L S T O, digo L I S T O."),
                new Quote("Homer Simpson", "¿Cuándo voy a aprender? La solución a todos los problemas de la vida no está en el fondo de una botella. ¡Está en la tele!"),
                new Quote("Homer Simpson", "¿Me podría decir dónde está el lavabo? Me gustaría fingir que me lavo las manos."),
                new Quote("Homer Simpson", "¿Qué pasaría si el rey de Inglaterra entrase en casa y comenzase a darte empujones? ¿Te gustaría, eh, te gustaría?"),
                new Quote("Homer Simpson", "¿Recuerdas aquella postal que nos envió el abuelo desde Florida de un aligátor mordiendo el trasero de una mujer? A todos nos pareció muy divertida. Pero estábamos equivocados. Ese aligátor estaba acosando sexualmente a esa mujer."),
                new Quote("Homer Simpson", "¿Y si era tan listo por qué está muerto?"),
                new Quote("Homer Simpson", "¿Y si nos equivocáramos de religión? Dios estaría más furioso cada semana."),
                new Quote("Homer Simpson", "“Para empezar presionar cualquier tecla” ¿Dónde está la tecla “cualquier”?"),
                new Quote("Homer Simpson", "A diferencia del amor, el respeto no se compra."),
                new Quote("Homer Simpson", "Ahora con Internet los niños se crían solos."),
                new Quote("Homer Simpson", "Cuando miro las caras sonrientes de los niños, solo sé que están planeando golpearme con algo."),
                new Quote("Homer Simpson", "El problema de las parejas es la comunicación… ¡demasiada comunicación!"),
                new Quote("Homer Simpson", "Hay dos tipos de estudiantes: los fuertes y los gilís. ¡Como atleta es mi deber hacerle la vida imposible a los gilís!"),
                new Quote("Homer Simpson", "He llegado a odiar mi propia creación, ahora sé cómo se siente Dios."),
                new Quote("Homer Simpson", "Hijos, os habéis esforzado. Y, ¿para qué? Para hacer el ridículo. La moraleja es: No os esforcéis."),
                new Quote("Homer Simpson", "La gente se inventa estadísticas con tal de demostrar cualquier cosa, y eso lo sabe el 91% de la gente."),
                new Quote("Homer Simpson", "La menopausia es cuando a una cigüeña le pega un disparo un cazador borracho."),
                new Quote("Homer Simpson", "La vida es un fracaso tras otro hasta que empiezas a desear que se muera Flanders."),
                new Quote("Homer Simpson", "Librarte de formar parte de un jurado popular es fácil. Solo tienes que decir que tienes prejuicios contra todas las razas."),
                new Quote("Homer Simpson", "Lisa, haz el favor. En esta casa obedecemos las leyes de la ¡termodinámica!"),
                new Quote("Homer Simpson", "Lisa, los vampiros son seres inventados, como los duendes, los gremlins y los esquimales."),
                new Quote("Homer Simpson", "Los viejos no necesitan amor, tienen que ser aislados y estudiados para ver qué nutrientes se les pueden extraer para nuestro beneficio personal."),
                new Quote("Homer Simpson", "Mar, retrete del mundo. Los griegos te llamaron Poseidón, los romanos, eeeeh Aquaman."),
                new Quote("Homer Simpson", "Marge, ¿cuántos hijos tenemos? ¡No! No tenemos tiempo para contar. Lo pondré a ojo: ¡nueve!"),
                new Quote("Homer Simpson", "Marge, ¿dónde está eso… esa cosa… que sirve para taca y a comer?"),
                new Quote("Homer Simpson", "Marge, Bart lleva una camisa hawaiana y solo dos tipos de hombres usan esas camisas, los gais y los juerguistas obesos, y Bart no tiene pinta de juerguista obeso."),
                new Quote("Homer Simpson", "Marge, eres tan hermosa como la Princesa Leia y tan lista como Yoda."),
                new Quote("Homer Simpson", "Marge, son las tres de la mañana, ¿no deberías estar cocinando?"),
                new Quote("Homer Simpson", "No es fácil organizarse con una mujer embarazada e hijos con problemas. Pero de alguna forma consigo organizarme para ver la televisión 8 horas al día."),
                new Quote("Homer Simpson", "No soy gordo, ¡es mi metabolismo!"),
                new Quote("Homer Simpson", "No veo por qué no puedo castigarles, son mis hijos, yo soy su dueño, (gruñido de Marge). ¡Está, bien, está bien! SOMOS sus dueños."),
                new Quote("Homer Simpson", "No voy a dejar de hablar a papá durante el resto de mi vida; sólo durante el resto de SU vida"),
                new Quote("Homer Simpson", "Normalmente no rezo, pero si estás ahí, por favor, sálvame Superman."),
                new Quote("Homer Simpson", "Nucelar, la palabra es nu-ce-lar."),
                new Quote("Homer Simpson", "Oh, si, ¿Qué vas a hacer? ¿Soltar los perros? ¿O las abejas? ¿O los perros con abejas en la boca para que cuando ladren las disparen contra ti?"),
                new Quote("Homer Simpson", "Operadora, deme el número del 091."),
                new Quote("Homer Simpson", "Para mentir se necesitan dos: Uno que mienta y otro que escuche."),
                new Quote("Homer Simpson", "Por la cerveza, causa y a la vez solución de todos los problemas de la vida."),
                new Quote("Homer Simpson", "Puede tener todo el dinero del mundo, pero hay algo que nunca podrá comprar... Un dinosaurio."),
                new Quote("Homer Simpson", "Quizá, por una vez alguien me llame ‘Señor’ sin añadir “Está usted montando una escena”."),
                new Quote("Homer Simpson", "Sabéis hijos, un reactor nuclear es como una mujer. Solo tienes que leer el manual y apretar los botones adecuados."),
                new Quote("Homer Simpson", "Si algo es difícil y duro de hacer, entonces no merece la pena hacerlo."),
                new Quote("Homer Simpson", "Sí, Marge, en teoría estoy contigo, pero en teoría funciona hasta el comunismo."),
                new Quote("Homer Simpson", "Sin tele y sin cerveza, Homer pierde la cabeza."),
                new Quote("Homer Simpson", "Solo porque no me importa no significa que no lo entienda."),
                new Quote("Homer Simpson", "Trabajo mucho y quiero a mis hijos, ¿por qué voy a pasar la mitad del domingo oyendo que me voy a ir al infierno?"),
                new Quote("Homer Simpson", "Tres pequeñas frases que te ayudarán a lo largo de tu vida: la primera ¡Cúbreme!, la segunda ¡Buena idea jefe!, y la tercera; Estaba así cuando llegué."),
                new Quote("Homer Simpson", "Tu siempre haces lo mismo Marge, siempre te pones de parte de un extraño: Flanders, el departamento de aguas, Dios."),
                new Quote("Homer Simpson", "Voy a matar a Moe… Wiiiiii… Voy a matar a Moe… Wiiii."),
                new Quote("Homer Simpson", "Y para beber, albóndigas."),
                new Quote("Homer Simpson", "Ya me conoces, Marge, me gusta la cerveza fría, la tele a todo volumen y que los gais revoloteen."),
                new Quote("Bart Simpson", "¡Ay, caramba!"),
                new Quote("Bart Simpson", "¡Milhouse, ¿cómo alguien con unas gafas tan grandes puede ser tan tonto?!"),
                new Quote("Bart Simpson", "¡Yo no he sido!"),
                new Quote("Bart Simpson", "¿Besarte? ¡Papá, sólo soy tu hijo!"),
                new Quote("Bart Simpson", "¿Que te ha pasado tío? Tu antes molabas."),
                new Quote("Bart Simpson", "¿Y para qué estudiar? Cuando sea grande quiero ser un gordo discapacitado como mi papá."),
                new Quote("Bart Simpson", "Esta salsa está más buena que el sudor de Dios."),
                new Quote("Bart Simpson", "judías, judías legumbre musical. Cuántas más comas más música habrá."),
                new Quote("Bart Simpson", "Las acciones valen cero… ¡pero tengo 52 millones de acciones! ¿Cuánto es 52 por cero…? ¡no me digas que es cero!"),
                new Quote("Bart Simpson", "Lisa, tú tienes la inteligencia para llegar hasta donde quieras. Y cuando llegues, yo estaré contigo para pedirte prestado."),
                new Quote("Bart Simpson", "Menos mal que recuperamos la cordura y adoramos a un carpintero que vivió hace 2000 años."),
                new Quote("Bart Simpson", "Multiplícate por cero."),
                new Quote("Bart Simpson", "Ningún niño debería vivir más que su mascota."),
                new Quote("Bart Simpson", "No te prometo que lo intentaré, pero intentaré intentarlo."),
                new Quote("Bart Simpson", "Oh, América, eres estupenda, pero no tanto como mi menda."),
                new Quote("Bart Simpson", "Oye, Otto, ¡tengo un examen hoy y no estoy listo! ¿Podrías estrellar el autobús o algo?"),
                new Quote("Bart Simpson", "Papá, es difícil no hacer caso a la televisión; pasa más horas educándonos que tú."),
                new Quote("Bart Simpson", "Querido Dios, nosotros pagamos por toda esta comida así que gracias por nada (bendiciendo la mesa)."),
                new Quote("Bart Simpson", "Si la televisión me ha enseñado algo es que los milagros les pueden suceder a niños pobres en navidad. Le pasó al pequeño Tim, le pasó a Charlie Brown, les pasó a los pitufos y ¡también a nosotros!"),
                new Quote("Bart Simpson", "Vive deprisa, muere joven y deja un cadáver obeso."),
                new Quote("Lisa Simpson", "¿Ser yo misma? He sido yo misma por 8 años y no ha funcionado."),
                new Quote("Lisa Simpson", "‘Cuando me case, mantendré mi apellido’… mmm, quizá debería decir ‘si decido casarme’"),
                new Quote("Lisa Simpson", "Antes de cantar el himno nacional me gustaría decir que el fútbol utiliza recursos que se podrían invertir en la educación y las artes."),
                new Quote("Lisa Simpson", "Cállate, cerebro. Ahora tengo amigos, ya no te necesito."),
                new Quote("Lisa Simpson", "Cuesta trabajo creer que un expresidiario como el actor secundario Bob haya obtenido tantos votos y otro expresidiario como Quimby haya obtenido tan pocos."),
                new Quote("Lisa Simpson", "Hola ardillita. ¿Sabes que eres una ardilla reticulada del norte? Que si, que eres muy reticulada."),
                new Quote("Lisa Simpson", "La felicidad es inversamente proporcional a la inteligencia."),
                new Quote("Lisa Simpson", "Las personas que acusan a otras de ser gais con frecuencia encubren su propia homosexualidad latente"),
                new Quote("Lisa Simpson", "Pienso que nada tiene sentido, todo seguiría igual si yo no hubiera nacido, ¿Como podemos dormir habiendo tanto sufrimiento en el mundo?"),
                new Quote("Lisa Simpson", "Si alguien me necesita estaré en mi habitación."),
                new Quote("Marge Simpson", "¡Bart, deja de molestar a Satanás!"),
                new Quote("Marge Simpson", "¡Tengo que salvarle! Si no nunca podre decirle «Ya te lo dije»."),
                new Quote("Marge Simpson", "Ay, ¡Homer haz algo! Ahora Bart bebe sangre, ¡pero mañana podría empezar a fumar!"),
                new Quote("Marge Simpson", "El sistema judicial ya no funciona, pero mientras todo el mundo filme así a todo el mundo, la justicia prevalecerá."),
                new Quote("Marge Simpson", "En un momento así, solo se puede reír."),
                new Quote("Marge Simpson", "Haz como decía mi madre: No hables, no digas nada, no llames la atención y se fuerte."),
                new Quote("Marge Simpson", "Mi tío Arturo solía decir: «Mátalos a todos y que Dios los seleccione». Un día decidió llevarlo a la práctica. Hicieron falta setenta y cinco agentes para detenerlo. ¡Y no quiero que volvamos a hablar de ello nunca más!"),
                new Quote("Marge Simpson", "Si puedo alimentar una familia de cinco con doce dólares a la semana, puedo hacerlo."),
                new Quote("Marge Simpson", "Todo el mundo hace locuras en los anuncios, como comer en un Burger."),
                new Quote("Marge Simpson", "Yo creía que buscarse en Google significaba otra cosa."),
                new Quote("Marge Simpson", "Mi vida es muy aburrida. La semana pasada vino un testigo de Jehová y yo no lo dejaba ir. Escapó cuando fui a la cocina a buscar más limonada."),
                new Quote("Helen Lovejoy", " ¡¿Pero es que nadie va a pensar en los niños?!"),
                new Quote("Ralph", "La señora Carapapel y el director estaban en un armario haciendo bebés, yo vi a uno de los bebés, y uno de los bebés se quedó mirándome."),
                new Quote("Milhouse", "¿Te acuerdas de Alf? ¡Ha vuelto! ¡Y en forma de chapas!"),
                new Quote("Troy McClure", "Si una vaca pudiera, te comería a ti y a todos tus seres queridos."),
                new Quote("Milhouse", "¡Todo ha salido a pedir de Milhouse!"),
                new Quote("Sr. Burns", "Familia, amistad y religión, tres demonios a destruir si quieres triunfar en los negocios."),
                new Quote("Abe Simpson", "¿Por qué me están evitando? ¿Mi cara marchita le recuerda al lúgubre espectro de la muerte?"),
                new Quote("Ralph", "¡Soy un unicornio retrasado!"),
                new Quote("Barney", "Dicen que el alcohol borra la memoria… de lo demás no me acuerdo."),
                new Quote("Barney", "¡Oh, no! ¡Elecciones! ¿Es uno de esos días en que cierran las tabernas, no es cierto?"),
                new Quote("Actor Secundario Bob", "Estoy en la cárcel por un delito que no cometí, ¡intento de asesinato! ¿Y qué significa eso de intento? ¿Acaso conceden el Premio Nobel por el Intento de Química?"),
                new Quote("Sr. Burns", "La opresión y la tiranía son una pequeña tasa por vivir en el país de la libertad."),
                new Quote("Moe", "¿Cuánto cobran los extras de cine? Porque dicen que me parezco a Macaulay Culkin."),
                new Quote("Apu", "No me interesa comprar su casa. Pero quisiera utilizar su baño, ojear sus revistas, reordenar sus figuras y manosear su comida de forma antihigiénica. ¡Ja! Ahora saben lo que se siente."),
                new Quote("Apu", "Todos tenemos sueños.... como mi antiguo sueño de venir a America y tener una familia.... ¡O mi nuevo sueño de abandonar a mi familia y fugarme a Canada!"),
                new Quote("Abe Simpson", "Siento la fría mano de la muerte sobre mi hombro… ¡Oh, no, es mi mano!"),
                new Quote("Jebediah Springfield", "Un noble espíritu engrandece al hombre más pequeño."),
                new Quote("Hans Topo", "Creo que nunca más volveré a ver, mi vista no se enderezará."),
                new Quote("Otto", "¡Puedo volar, puedo volar! Es broma… sé que no puedo volar… ¡Pero sí puedo planear, puedo planear!"),
                new Quote("Otto", "Oiga, todo lo que sé hacer es conducir un autobús, ¡y ahora quiere que tenga permiso para ello!"),
                new Quote("Moe", "tenía una muñeca hinchable… y ella también me abandonó. No debí usar helio."),
                new Quote("Milhouse", "Empezamos como Romeo y Julieta, ¿cómo pudo terminar en tragedia?"),
                new Quote("Ralph", "El aliento de mi gato huele a comida de gato."),
                new Quote("Moe", "Vas por la vida tratando de ser bueno con la gente, tratas de resistirte ante la tentación de golpearlos en la cara, ¿y todo para qué?"),
                new Quote("Moe", "Tarde o temprano, a todos nos disparan."),
                new Quote("Moe", "Ah, se creen todopoderosos sólo porque nunca los han sorprendido conduciendo sin pantalones."),
                new Quote("Ralph", "¿Que voy mal en lengua? Eso no posible es."),
                new Quote("Skinner", "¿No es agradable que odiemos la misma cosa?"),
                new Quote("Troy McClure", "Si una vaca pudiera, te comería a ti y a todos tus seres queridos."),
                new Quote("Homer Simpson", "Oh poderoso Dios del océano, los griegos te llamaban Poseidón y los romanos... Acuaman."),
                new Quote("Homer Simpson", "El matrimonio es como un ataud y cada hijo es otro clavo..."),
                new Quote("Homer Simpson", "Hay tres tipos de personas : las que saben contar y las que no."),
                new Quote("Homer Simpson", "Intentarlo es el primer paso hacia el fracaso."),
                new Quote("Homer Simpson", "Solo porque no me importe no significa que no entienda."),
                new Quote("Homer Simpson", "Bart, no quiero alarmarte, pero creo que el Coco, ¡si, el Coco!, está en la casa."),
                new Quote("Homer Simpson", "Cerveza: causa y solución de todos los problemas."),
                new Quote("Homer Simpson", "¿Cómo se supone que la educación me va a hacer más listo? Al contrario, cada vez que aprendo algo nuevo, algo que ya sabía desaparece de mi cerebro. ¿Recuerdas cuando hice ese curso de fabricación de vino en casa y se me olvidó conducir?"),
                new Quote("Abe Simpson", "Mi hijo no es comunista. Podrá ser mentiroso, puerco, idiota, comunista, pero nunca una estrella de porno."),
                new Quote("Abe Simpson", "Querido Señor Presidente: hay demasiados Estados hoy en día, por favor elimíne tres. No soy un viejo maniático."),
                new Quote("Abe Simpson", "Dicen que la mayor tragedia para un padre es que su hijo muera. Yo nunca he entendido por qué lo dicen, francamente yo le vería el lado positivo."),
                new Quote("Abe Simpson", "Hijo, si alguna vez viajas atrás en el tiempo, procura no tocar nada."),
                new Quote("Abe Simpson", "Lo he oído todo, lo he visto todo, lo he hecho todo. Sólo que no recuerdo nada."),
                new Quote("Sr. Burns", "¡Qué hacen en mi alcantarilla para cadáveres! Alcantarilla para cadáveres, quise decir tubería de la inocencia."),
                new Quote("Sr. Burns", "Ah, lunes a la mañana, hora de pagar por sus 2 días de ocio, zánganos miserables."),
                new Quote("Sr. Burns", "¿Un dólar por felicidad eterna? Mmm... Prefiero el dólar."),
                new Quote("Sr. Burns", "Familia, religión, amistad. Estos son los tres demonios usted debe matar si desea tener éxito en los negocios."),
                new Quote("Homer Simpson", "Te advierto que si vas a enfadarte conmigo cada vez que haga una estupidez, no tendré más remedio que dejar de hacer estupideces."),
                new Quote("Barney", "No hay nada mejor que la cerveza para darle a uno esa falsa sensación de bienestar."),
                new Quote("Homer Simpson", "Me voy al asiento trasero de mi coche, con la mujer que amo, ¡Y no volveré en 10 minutos!"),
                new Quote("Homer Simpson", "En mi familia somos 5 personas: Marge, Bart, la niña Bart, la que nunca habla y el tipo gordo, cómo lo desprecio."),
                new Quote("Homer Simpson", "Desearía que Dios estuviera vivo para ver esto."),
                new Quote("Homer Simpson", "Si algo hemos aprendido de los Picapiedra es que los pelícanos sirven para mezclar cemento."),
                new Quote("Homer Simpson", "Marge, niños, les prometo que todo va a salir bien. Vayan arriba, empaquen sus maletas. Vamos a comenzar una nueva vida…Bajo el mar."),
                new Quote("Homer Simpson", "Me mata verla así y si hay algo que no soporto, es que me maten."),
                new Quote("Reverendo Lovejoy", "Casi todo es pecado. ¿Te has puesto a leer la Biblia con calma? Técnicamente es pecado ir al baño."),
                new Quote("Reverendo Lovejoy", "La iglesia te lo da, la iglesia te lo quita."),
                new Quote("Reverendo Lovejoy", "Vino en paz y luego murió. Y enseguida volvió a la vida. y su nombre era... E.T. el extraterrestre... snif, amo a ese pequeñín."),
                new Quote("Carl", "Todo el mundo comete errores. Por eso ponen gomas de borrar en los lápices."),
                new Quote("Carl", "Sabes, estoy cansado de que la gente crea que soy bueno jugando al basketball sólo porque soy negro."),
                new Quote("Edna Krabappel", "Recuerden, niños: mientras peor salga el exámen, más fondos nos dan, así que no se esfuercen mucho."),
                new Quote("Edna Krabappel", "No quiero que se preocupen, niños, estas pruebas no tienen efecto sobre sus notas. Sólo determina su futuro nivel social y éxito financiero. Si es que lo tienen."),
                new Quote("Clancy Wiggum", "Espero que esto le haya enseñado a sus niños una lección: los niños nunca aprenden."),
                new Quote("Clancy Wiggum", "Lee la placa, hijo: ¡Los sobornos son sólo en efectivo!"),
                new Quote("Doctor Hibbert", "Me temo que su esposo ha muerto... ¡jo jo! ¡sólo bromeaba!"),
                new Quote("Kent Brockman", "¿No es esto lo que todos nos preguntamos en la vida: dónde está mi elefante? Por lo menos yo, sí."),
                new Quote("Lenny", "Lo mío con la vecina se acabó. Ha puesto una persiana."),
                new Quote("Ned Flanders", "Si es suave y amarillo, seguro que es juguillo, si es turbio y picozón, es sidra muchachón."),
                new Quote("Ned Flanders", "¡Por supuesto que soy aficionado a los Beatles. ¡Ellos fueron más grandes que Jesús!"),
                new Quote("Ned Flanders", "He hecho todo que la Biblia dice ¡incluso cuando una cosa contradice a otra cosa!"),
                new Quote("Selma Bouvier", "Desde ahora sólo me casaré por amor. Tal vez una vez más por dinero."),
                new Quote("Fat Tony", "Mi esposa fue asesinada por causas naturales."),
                new Quote("Willie", "Si me hicieran alcalde, mi primer acto sería matarlos a todos ustedes y quemar su maldita ciudad."),
                new Quote("Willie", "¡No existe un animal vivo que pueda escapar de un escocés engrasado!"),
                new Quote("Nelson", "Mi padre no me abandonó, sólo se fue al mercado... ¿verdad que si, mami?")
        );
        quoteRepository.deleteAll();
        quoteRepository.saveAll(FRASES_SIMPSONS);
    }
}
