version: '3'
services:
    frontend:
        build:
            context: ../quotes-frontend
        image: quotes-frontend
        ports:
            - 8081:8080
        environment:
            - "MICRONAUT_HTTP_SERVICES_CHARACTERS_URLS=http://backend:8080/"
            - "MICRONAUT_HTTP_SERVICES_QUOTES_URLS=http://backend:8080/"

    backend:
        build:
            context: ../quotes-backend
            dockerfile: Dockerfile.multi2
        image: quotes-backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - spring.data.mongodb.uri=mongodb://mongo/test

    mongo:
        image: mongo:3.6
