FROM maven:3.5-jdk-8 as maven
WORKDIR /app
COPY ./pom.xml /app/pom.xml
RUN mvn dependency:go-offline --batch-mode

COPY ./src /app/src
RUN mvn clean package -Dmaven.test.skip=true --batch-mode

FROM openjdk:8-jre-alpine
COPY --from=maven /app/target/quotes-backend-0.0.1.jar /myapp.jar
EXPOSE 8080
ENTRYPOINT java ${JAVA_OPTS} -jar /myapp.jar
